spring:
  profiles:
    active: @spring.profiles.active@

server:
  port: 5000

app:
  datasource:
    jdbc-url: jdbc:postgresql://fullstackspringbootdb.ccv2hskxklny.ap-south-1.rds.amazonaws.com:5432/amigoscodedemo
    username: amigoscode
    password: 123456789
    pool-size: 30